name: ci

on:
  push:
    branches: [ 'main', 'dev' ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'package*.json'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ 'main', 'dev' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: github checkout
        uses: actions/checkout@v3
      -
        name: docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=ref,event=pr
      -
        name: setup QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: docker login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push:   ${{ github.event_name != 'pull_request' }}
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
